# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yan-Ni (Annie) Tai
title: Data Analyst / Applied Statistics Master's Student
email: yannitai@umich.edu
website: https://github.com/yannitai

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  yannitai
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: yannitai
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I’m a recent graduate from the University of Michigan with a master’s degree in Applied Statistics and a passion for solving business problems through data. I bring hands-on experience in SQL, Python, Power BI, and Tableau, developed through internships and academic projects in time series forecasting, sentiment analysis, and machine learning.



  I am most skilled in: <mark>SQL</mark>, <mark>Python</mark>, <mark>Tableau</mark>, <mark>A/B Testing</mark>, and <mark>Statistical Modeling</mark>


content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  TSMC
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Data Analytics Intern – Intelligent Manufacturing
        caption: June 2024 – Aug 2024
        quote: >
          Leveraging SQL, Power BI, and manufacturing KPIs, I turned over 20 machines’ raw output into data-driven strategies that improved efficiency and reduced inspection rate by 10%.
        description: | # this will include new lines to allow paragraphs
          - Analyzed data from 20+ machines using SQL to identify anomalies and optimize production planning.
          - Built Power BI dashboards for real-time monitoring of key KPIs across manufacturing teams.
          - Reduced inspection effort by 10% by designing data-driven decision rules.
      
      - layout: left
        title:  Northeast and Yilan Coast National Scenic Area Administration
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Data Analyst Intern
        caption: Feb 2023 – Jun 2023
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Built an Excel tool that streamlined the organization of 2,000+ tourism records, cutting manual processing time by 20%.
          - Uncovered insights into visitor trends and behavior to inform strategic planning.

      - layout: left
        title:  National Cheng Kung University
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: Sep 2021 – Mar 2023
        # quote: >
          # Applied Python, ETL automation, and advanced statistical modeling to turn financial news into actionable forecasts.
        description: | # this will include new lines to allow paragraphs
          - Developed Python-based ETL pipelines to collect and process 60,000+ financial news records, streamlining data preparation for stock market research.
          - Built 10+ time series models to forecast stock price trends, resulting in improved accuracy and analysis efficiency.
          - Refined an alternative credit scoring model by applying weighted multiple regression, increasing predictive reliability and supporting better decisions.
          

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Passenger Transport Prediction
        link: https://github.com/yannitai/Spaceship_Titanic_Kaggle_Competition.git
        link_text: Spaceship_Titanic_Kaggle_Competition
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Leveraged **EDA**, **scikit-learn**, and **ensemble learning** to engineer end-to-end predictive workflows on transport data.
        description: | # this will include new lines to allow paragraphs
          - Identified key patterns in demographics and spending behavior by conducting exploratory data analysis (EDA) on 13,000+ passenger records using Python, supporting data-driven modeling decisions.
          - Achieved 80.3% prediction accuracy by developing end-to-end machine learning pipelines using scikit-learn and applying ensemble methods (Voting Classifier).
          
      - layout: top-middle
        title: Stock Market Analysis Using Deep Learning and NLP During the Covid-19 Pandemic 
        link: https://github.com/yannitai/stock_covid_nlp_analysis.git
        link_text: Stock_Market_Analysis
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Combined NLP, time series modeling, and COVID-19 data to enhance stock market forecasting, achieving a 30% improvement in trend prediction accuracy with LSTM models.
        description: | # this will include new lines to allow paragraphs
          - Scraped 60,000+ financial news articles and labeled sentiment using CKIP Tagger and a sentiment dictionary.
          - Merged sentiment, COVID-19 case counts, and technical indicators (MA, BIAS, momentum) for feature engineering.
          - Built ARIMA and LSTM models to forecast stock trends on TWII and sector indices.
          - Used expanding window cross-validation; LSTM + sentiment improved directional accuracy by 30%.
          - Demonstrated that combining financial NLP and pandemic data enhances market prediction during crises.
        
        


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Michigan — Ann Arbor 
        caption: 2023 - 2025
        sub_title: M.S. in Applied Statistics 
        #quote: >
         # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Relevant Coursework: Statistical learning, Data Management and Analysis, Data Science in Python, Database Design

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data analysis, some of my other interests and hobbies are:
      - NBA
      - Working Out
      - Surfing

    #  Look at this cool image  
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
