# Site
repository: yannitai/yannitai.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yan-Ni (Annie) Tai
title: Data Analyst / Applied Statistics Master's Student
email: yannitai@umich.edu
website: https://github.com/yannitai

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: yannitai
linkedin_username: yannitai

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.itsgoingto.be

# About Section
about_profile_image: images/profile.jpg
about_content: | 
  I’m a recent graduate from the University of Michigan with a master’s degree in Applied Statistics and a passion for solving business problems through data. I bring hands-on experience in SQL, Python, Power BI, and Tableau, developed through internships and academic projects in time series forecasting, sentiment analysis, and machine learning.

  I am most skilled in: <mark>SQL</mark>, <mark>Python</mark>, <mark>Tableau</mark>, <mark>A/B Testing</mark>, and <mark>Statistical Modeling</mark>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: TSMC (Taiwan Semiconductor Manufacturing Company)
        sub_title: Data Analytics Intern – Intelligent Manufacturing
        caption: June 2024 – Aug 2024
        description: |
          - Analyzed data from 20+ machines using SQL to identify anomalies and optimize production planning.
          - Built Power BI dashboards for real-time monitoring of key KPIs across manufacturing teams.
          - Reduced inspection effort by 10% by designing data-driven decision rules.

      - layout: left
        title: Northeast and Yilan Coast National Scenic Area Administration
        sub_title: Data Analyst Intern
        caption: Feb 2023 – Jun 2023
        description: |
          - Built an Excel tool that streamlined the organization of 2,000+ tourism records, cutting manual processing time by 20%.
          - Uncovered insights into visitor trends and behavior to inform strategic planning.

      - layout: left
        title: National Cheng Kung University
        sub_title: Research Assistant, Department of Statistics
        caption: Sep 2021 – Mar 2023
        description: |
          - Built Python ETL pipelines to process 60,000+ financial news articles for stock prediction models.
          - Developed 10+ time series models and an improved credit scoring method using weighted regression.

  - title: Education
    layout:
